/**
 * Tool Executor
 *
 * Ejecuta los tools que el LLM decide usar.
 * Por ahora implementa getInstructorReport que llama al endpoint /api/reports/instructor.
 */

import Instructor from '../../../models/Instructor.js';
import Schedule from '../../../models/Schedule.js';
import OthersSchedule from '../../../models/OthersSchedule.js';

/**
 * Busca un instructor por nombre y devuelve su ObjectId
 * @param {string} instructorName - Nombre del instructor
 * @returns {Promise<string>} - ObjectId del instructor
 * @throws {Error} - Si no encuentra el instructor
 */
async function findInstructorByName(instructorName) {
  console.log(`🔍 Buscando instructor: "${instructorName}"`);

  // Búsqueda case-insensitive
  const instructors = await Instructor.find({
    name: { $regex: instructorName, $options: 'i' }
  }).limit(5);

  if (instructors.length === 0) {
    throw new Error(`No se encontró ningún instructor con el nombre "${instructorName}"`);
  }

  // Si hay múltiples coincidencias, retornar la primera
  // (podríamos implementar lógica más inteligente para elegir el mejor match)
  const instructor = instructors[0];
  console.log(`✅ Instructor encontrado: ${instructor.name} (${instructor._id})`);

  return instructor._id.toString();
}

/**
 * Calcula las horas trabajadas (lógica extraída de reports.controller.js)
 */
function calculateHours(events, tstart, tend, fstart, fend) {
  let totalHours = 0;

  const startDate = new Date(fstart);
  const endDate = new Date(fend);

  // Parsear horas de inicio y fin (formato "HH:MM")
  const [startHour, startMin] = tstart.split(':').map(Number);
  const [endHour, endMin] = tend.split(':').map(Number);

  // Calcular duración en minutos de una sesión
  const diference = (endHour * 60 + endMin) - (startHour * 60 + startMin);
  const minutes = Math.round(diference);
  const durationHours = parseFloat(minutes / 60).toFixed(2);

  events.forEach((event) => {
    const eventDate = new Date(event);

    // Verificar si el evento está dentro del rango de fechas
    if (eventDate >= startDate && eventDate <= endDate) {
      totalHours += parseFloat(durationHours);
    }
  });

  return totalHours;
}

/**
 * Formatea fecha a formato 12 horas
 */
function formatDate12Hours(time24) {
  const [hours, minutes] = time24.split(':');
  const hour = parseInt(hours);
  const ampm = hour >= 12 ? 'P.M.' : 'A.M.';
  const hour12 = hour % 12 || 12;
  return `${hour12}:${minutes} ${ampm}`;
}

/**
 * Genera colores aleatorios para eventos
 */
const colorsEvents = [
  { background: '#ADFF2F', colortext: '#000000' },
  { background: '#FFC0CB', colortext: '#000000' },
  { background: '#228B22', colortext: '#FFFFFF' },
  { background: '#00FF00', colortext: '#000000' },
  { background: '#98D8C8', colortext: '#000000' },
  { background: '#00BFFF', colortext: '#000000' },
  { background: '#FF69B4', colortext: '#000000' },
];

/**
 * Formatea un evento de horario
 */
function formatEventSchedule(progra, event, index, color, isOther, ficheNumber) {
  return {
    id: index,
    code: progra._id,
    fiche: ficheNumber || progra.fiche?.number || '',
    idInstructor: progra.instructor._id,
    instructor: progra.instructor.name,
    title: ficheNumber || progra.program?.name || '',
    program: progra.program?.name || '',
    supporttext: progra.supporttext || '',
    observation: progra.observation || '',
    environment: progra.environment?.name || '',
    outcome: progra.outcome?.name || '',
    competence: progra.competence?.name || '',
    start: new Date(event).toISOString().split('T')[0],
    tstart: formatDate12Hours(progra.tstart),
    tend: formatDate12Hours(progra.tend),
    backgroundColor: color.background || color,
    borderColor: color.background || color,
    textColor: color.colortext || '#000000',
    type: isOther ? 1 : 0,
    autogenerated: false
  };
}

/**
 * Ejecuta el tool getInstructorReport
 * @param {Object} parameters - Parámetros del tool
 * @returns {Promise<Object>} - Resultados del reporte
 */
async function executeGetInstructorReport(parameters) {
  const { instructor, fstart, fend } = parameters;

  console.log('\n📊 Ejecutando tool getInstructorReport...');
  console.log(`   Instructor: ${instructor}`);
  console.log(`   Fecha inicio: ${fstart}`);
  console.log(`   Fecha fin: ${fend}`);

  try {
    // 1. Buscar el instructor por nombre para obtener ObjectId
    const instructorId = await findInstructorByName(instructor);

    // 2. Buscar horarios del instructor
    const schedules = await Schedule.find({
      instructor: instructorId,
      status: 0,
    }).populate('fiche instructor program competence outcome environment');

    const otherSchedule = await OthersSchedule.find({
      instructor: instructorId,
      status: 0,
    }).populate('instructor');

    // 3. Procesar datos
    let daysProgram = {};
    let colors = [...colorsEvents];
    let hourswork1 = 0;
    let hourswork2 = 0;

    const newFstart = new Date(fstart);
    const newFend = new Date(fend);

    // Capturar los meses entre las fechas
    let dates = [];
    let yearsMonth = [];
    let month = newFstart.getUTCMonth() + 1;
    let tempDateStart = new Date(newFstart);

    while (tempDateStart <= newFend) {
      dates.push(month.toString().padStart(2, '0'));
      yearsMonth.push(
        `${tempDateStart.getUTCFullYear()}-${month.toString().padStart(2, '0')}`
      );

      if (month === 12) {
        month = 0;
      }

      month++;
      tempDateStart.setMonth(tempDateStart.getMonth() + 1);
    }

    // Extraer eventos de programaciones normales
    let newListProgramaFiche = [];
    schedules.forEach((progra) => {
      if (progra.fstart <= newFend && progra.fend >= newFstart) {
        newListProgramaFiche.push(progra);
      }
    });

    let index = 1;
    let colorsFiche = {};

    newListProgramaFiche.forEach((progra) => {
      let color;
      if (colorsFiche[progra.fiche.number]) {
        color = colorsFiche[progra.fiche.number];
      } else {
        color = colors[Math.floor(Math.random() * colors.length)];
        colors.splice(colors.indexOf(color), 1);
        colorsFiche[progra.fiche.number] = color;
      }

      hourswork1 += calculateHours(
        progra.events,
        progra.tstart,
        progra.tend,
        newFstart,
        newFend
      );

      progra.events.forEach((event) => {
        const newDate = new Date(event);
        const month = (newDate.getUTCMonth() + 1).toString().padStart(2, '0');

        if (dates.includes(month)) {
          if (daysProgram[month]) {
            daysProgram[month].push(
              formatEventSchedule(
                progra,
                event,
                index,
                color,
                false,
                progra.fiche.number
              )
            );
          } else {
            daysProgram[month] = [];
            daysProgram[month].push(
              formatEventSchedule(
                progra,
                event,
                index,
                color,
                false,
                progra.fiche.number
              )
            );
          }
          index++;
        }
      });
    });

    // Extraer eventos de otras programaciones
    let newListOtherSchedule = [];
    otherSchedule.forEach((progra) => {
      if (progra.fstart <= newFend && progra.fend >= newFstart) {
        newListOtherSchedule.push(progra);
      }
    });

    newListOtherSchedule.forEach((progra) => {
      hourswork2 += calculateHours(
        progra.events,
        progra.tstart,
        progra.tend,
        newFstart,
        newFend
      );

      let color;
      if (colorsFiche[progra.typeactivity]) {
        color = colorsFiche[progra.typeactivity];
      } else {
        color = colors[Math.floor(Math.random() * colors.length)];
        colors.splice(colors.indexOf(color), 1);
        colorsFiche[progra.typeactivity] = color;
      }

      progra.events.forEach((event) => {
        const newDate = new Date(event);
        const month = (newDate.getUTCMonth() + 1).toString().padStart(2, '0');

        if (dates.includes(month)) {
          if (daysProgram[month]) {
            daysProgram[month].push({
              id: index,
              idInstructor: progra.instructor._id,
              typeactivity: progra.typeactivity,
              additionalactivity: progra.additionalactivity,
              justification: progra.justification,
              title: 'ACTIVIDAD COMPLEMENTARIA',
              instructor: progra.instructor.name,
              start: event.toISOString().split('T')[0],
              tstart: formatDate12Hours(progra.tstart),
              tend: formatDate12Hours(progra.tend),
              backgroundColor: color.background,
              borderColor: color.background,
              textColor: color.colortext,
              type: 1,
            });
          } else {
            daysProgram[month] = [];
            daysProgram[month].push({
              id: index,
              idInstructor: progra.instructor._id,
              typeactivity: progra.typeactivity,
              additionalactivity: progra.additionalactivity,
              justification: progra.justification,
              title: 'ACTIVIDAD COMPLEMENTARIA',
              instructor: progra.instructor.name,
              start: event.toISOString().split('T')[0],
              tstart: formatDate12Hours(progra.tstart),
              tend: formatDate12Hours(progra.tend),
              backgroundColor: color.background,
              borderColor: color.background,
              textColor: color.colortext,
              type: 1,
            });
          }
          index++;
        }
      });
    });

    // 4. Construir respuesta
    const report = {
      msg: 'Reporte generado correctamente',
      months: dates,
      instructor: schedules[0]
        ? schedules[0].instructor.name
        : otherSchedule[0]
        ? otherSchedule[0].instructor.name
        : '',
      yearsMonth,
      hoursworkFormacion: hourswork1,
      hoursworkOthers: hourswork2,
      events: daysProgram,
    };

    console.log('✅ Reporte generado exitosamente');
    console.log(`   Horas formación: ${report.hoursworkFormacion}`);
    console.log(`   Horas otras: ${report.hoursworkOthers}`);

    return report;

  } catch (error) {
    console.error('❌ Error ejecutando getInstructorReport:', error);
    throw error;
  }
}

/**
 * Ejecuta un tool específico
 * @param {string} toolName - Nombre del tool a ejecutar
 * @param {Object} parameters - Parámetros del tool
 * @returns {Promise<Object>} - Resultados del tool
 */
export async function executeTool(toolName, parameters) {
  console.log(`\n🔧 Ejecutando tool: ${toolName}`);

  switch (toolName) {
    case 'getInstructorReport':
      return await executeGetInstructorReport(parameters);

    default:
      throw new Error(`Tool no implementado: ${toolName}`);
  }
}

export default {
  executeTool,
  executeGetInstructorReport,
  findInstructorByName
};
